Feature/회원 관리 api #106
Untoc-Web-Develop/Untoc-Front pull request #107
Opened 2024-03-26 10:29 UTC by hdh4952

## 관련이슈

- close #106 

## 요약

회원 정보를 불러오는 api 연결 및 회원 활동 상태 변경 api 연결

## 상세

- 뱃지 관련 추가 작업 필요

## 리뷰안내

- 리뷰 예상 소요 시간: 10분
- 참고사항
- 프리뷰이미지
![image](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/6864dd9e-d884-4fe5-b497-365a977fd3e7)

2024-03-26 18:03 UTC, jimini1026 approved these changes

2024-03-27 03:22 UTC, jasper200207 requested changes
코멘트 확인 바랍니다

2024-03-27 03:22 UTC, jasper200207 commented on src/page/Admin/AdminManageUser/AdminManageUser.jsx
> +  }, [usersData]);
여기 useEffect를 사용한 특별한 이유가 있나요..?
useQuery로 불러오는 데이터는 State처럼 업데이트가 되면 다시 렌더링 되기 때문에 useState&useEffect로 다시 사용하는 건 별로 좋지 않은거 같습니다.

2024-03-27 03:22 UTC, jasper200207 commented on src/page/Admin/AdminManageUser/AdminManageUser.jsx
>          <DataGrid disableRowSelectionOnClick rows={users} columns={columns} pageSizeOptions={[100]} />
여기에 users 대신 usersData.data 사용하는게 좋아보입니다.

2024-03-27 04:23 UTC, hdh4952 commented on src/page/Admin/AdminManageUser/AdminManageUser.jsx
> +  }, [usersData]);
처음엔 유저 활동 상태 변경을 바로 적용하지 않고 값을 가지고 있다가 저장 버튼을 눌렀을 때 업데이트 시키려고 했는데 바로 적용되도록 구현하는 과정에서 useEffect를 쓴 게 남았네요.. 감사합니다

2024-03-27 05:12 UTC, jasper200207 approved these changes
👍

2024-03-27 08:05 UTC, kbs1027 approved these changes
굳

2024-03-27 08:33 UTC, merged