feat : 회원가입 페이지 연결
Untoc-Web-Develop/Untoc-Front pull request #112
Opened 2024-03-28 06:42 UTC by jimini1026

## 관련이슈

- #79 

## 요약

- api 연결

## 상세

- 이메일, 이메일 인증코드, 회원가입 api에 연결 완료
- 회원가입 버튼 누르면 백엔드 쪽에서 에러 발생(범수 선배가 말씀하신 에러)

## 리뷰안내

- 리뷰 예상 소요 시간 : 20분
- 참고사항
- 프리뷰이미지
![localhost_3000_register (4)](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/7d991c7b-d728-48fa-b196-2f50afa3776f)

2024-03-28 09:08 UTC, mun-kyeong approved these changes
api 연결이군요!! 좋습니다 수고하셨어요 :)

2024-03-28 14:22 UTC, hdh4952 requested changes
코멘트 확인 부탁합니다

2024-03-28 14:22 UTC, hdh4952 commented on src/api/registerApi.js
> +  };
fetcher의 리턴에 중괄호가 포함되면 안된다고 하네요.. 
https://github.com/Untoc-Web-Develop/Untoc-Front/pull/104#discussion_r1537123033

2024-03-28 14:22 UTC, hdh4952 commented on src/api/registerApi.js
> +  };
같은 이슈입니다

2024-03-28 14:22 UTC, hdh4952 commented on src/api/registerApi.js
> +  };
이것도 같네요

2024-03-28 21:51 UTC, jasper200207 approved these changes
👍

2024-03-31 04:10 UTC, hdh4952 approved these changes
👍

2024-03-31 04:11 UTC, merged