feat: 비밀번호 찾기 페이지 연결
Untoc-Web-Develop/Untoc-Front pull request #113
Opened 2024-03-31 06:39 UTC by jimini1026

## 관련이슈

- close #103 

## 요약

api 연결하였습니다

## 상세

- api 연결
- 이메일 및 인증코드 api 함수는 공통 컴포넌트로 이동
- 인증확인 UI 추가
- 로직 수정 중

## 리뷰안내

- 리뷰 예상 소요 시간 : 20분
- 참고사항
- 프리뷰이미지
![image](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/591eb25b-43b1-4064-a6ad-eec99920b009)

2024-03-31 08:14 UTC, hdh4952 approved these changes
👍

2024-03-31 08:40 UTC, jasper200207 requested changes
코멘트 확인해주세요

2024-03-31 08:40 UTC, jasper200207 commented on src/api/registerApi.js
> +export default usePostRegisterMutation;
이거 형식맞춰서 {}안에 넣고 위에 eslint 비활성화 하는게 좋아보입니다.

2024-03-31 08:40 UTC, jasper200207 commented on src/page/FindPassword/FindPassword.jsx
> +    console.log(JSON.stringify(data));
콘솔로그는 빼주세요

2024-03-31 13:32 UTC, jimini1026 commented on src/page/FindPassword/FindPassword.jsx
> +    console.log(JSON.stringify(data));
반영했슴다..!

2024-04-01 05:59 UTC, jasper200207 approved these changes
👍

2024-04-01 06:01 UTC, merged