feat : 신입 회원 모집 페이지 레이아웃 추가
Untoc-Web-Develop/Untoc-Front pull request #29
Opened 2023-11-07 09:29 UTC by hdh4952

## 관련이슈

- #2 

## 요약

신입 회원 모집 페이지 레이아웃 추가

## 상세

- 전체 페이지 화면을 세로로 2분할하여 작업함
- 모든 글자를 하드코딩하여 이후 변경이 필요함

## 리뷰안내

- 리뷰 예상 소요 시간
  - 5분
- 프리뷰이미지
<img width="1280" alt="스크린샷 2023-11-07 181954" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/b379ac5b-d5ba-4eeb-8230-15ebcb2fb89e">

2023-11-07 13:47 UTC, kbs1027 submitted a review, later dismissed

2023-11-07 17:00 UTC, jasper200207 requested changes
이미지 경로와 #FFFFFF와 같은 기존에 있는 색상코드만 바꾸면 좋을 듯 합니다. 추가적으로 css 속성 넣을 때, 크기를 제외한 경우에는 되도록이면 px단위를 바로 쓰기 보다는 기존에 있는 설정을 넣으면 좋을거 같습니다.

2023-11-07 17:00 UTC, jasper200207 commented on src/page/Recruit/RecruitDescription.jsx
> +import RecruitImg from '../../asset/recruitImg.png';
js paths 설정이 되어있어서 상대경로 보다는 ```"asset/recruitImg.png"``` 로 불러오는게 좋을 듯 합니다.
추가로 asset에 바로 이미지를 넣지말고 해당 페이지에서만 사용하는 이미지는 페이지 이름 폴더안에 넣으면 추후에 찾아서 관리하기 좋을거 같습니다.
이 경우에는 예시로 ```"asset/recruit/mainImg.png"``` 로 하면 좋을 듯 합니다.

2023-11-07 17:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +const RecruitForm = () => {
이 컴포넌트는 추후에 react-hook-form으로 바꾸면 좋을 듯 합니다. 아직 설치가 안되어 있어서 나중에 사용법 알려주고 설치 PR 머지되면 수정하면 될거 같습니다.

2023-11-07 17:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +      <div className="h-[68px] w-[200px] bg-[#FFFFFF] absolute top-[-45px] left-[0] flex justify-center items-center rounded-t-[10px] text-lg text-[#FFBD00]">
색상 넣을 때, 되도록이면 색상코드 바로 넣지말고 색상이름으로 넣는게 좋아보입니다. 특히 "#FFFFFF"같은 경우는 white로 기본값 있으니 그거 사용하는게 좋을 듯 합니다. 피그마에 있는 색상은 대부분 https://github.com/Untoc-Web-Develop/Untoc-Front/pull/27 에 tailwindcss 설정으로 넣어뒀으니 일단 색상코드 넣었다가 나중에 이름으로 바꾸면 좋을 듯 합니다.

2023-11-07 17:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +          <input type="button" value="취소" className="h-7 w-1/4 border border-[#DDE1E6] rounded-[5px]" />
여기 rounded 속성을 넣을 때, px단위로 바로 넣기 보다는 되도록이면 2xl 같은 단위를 사용하는게 알아보기 좋을듯 합니다.

2023-11-12 17:18 UTC, mun-kyeong reviewed
comment 확인 부탁해요! 
이런 방법이 어떨까- 정도라서 확인하고 의견 남겨주면 approve 할께요 :)

2023-11-12 17:18 UTC, mun-kyeong commented on src/page/Recruit/RecruitDescription.jsx
> +        <h1 className="text-4xl mb-16">UntoC 16기 신입회원 모집</h1>
얘네 나중에 변수값으로 다 변경 되는 값들인거죠? 
신입회원모집 - 관리자 권한에서 기수, 날자, 안내 내용이랑 전부 다 바뀌는 내용입니다!!

2023-11-12 17:18 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +              <input
그냥 든 생각이긴 한데 얘네 정보만 들어갈 페이지 하나 만들어서 그거 이 페이지에 import 하고 map 돌리는 형식으로 하면 조금 더 코드 예뻐지지 않을까,, 하는 생각이

2023-11-13 15:08 UTC, kbs1027 submitted a review, later dismissed

2023-11-14 05:37 UTC, hdh4952 commented on src/page/Recruit/RecruitForm.jsx
> +              <input
api 연결 작업 때 form hook을 이용해서 수정할게요 :)

2023-11-14 05:43 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +              <input
오 그거 좋네요 :) 굳입니다

2023-11-14 06:45 UTC, mun-kyeong approved these changes
수고하셨습니다! 굳이예용 :)

2023-11-14 07:29 UTC, jasper200207 approved these changes
큰 수정사항은 없어서 Approve 하겠습니다. 수고하셨습니다!

2023-11-14 07:29 UTC, jasper200207 commented on src/page/Recruit/RecruitDescription.jsx
> +        <h2 className="text-base text-[#FFBD00] mb-10">모집기간 : 2023.08.15 ~ 2023.08.31</h2>
여기 text-yellowPoint 로 안바꼈습니다

2023-11-14 07:29 UTC, jasper200207 commented on src/page/Recruit/RecruitDescription.jsx
> +        </p>
이거 <br />로 줄바꾸면 서버에서도 br 넣어야 해서 줄바꿈 문자 사용가능하도록 하면 좋을 듯 합니다.

```<p className="whitespace-pre-wrap">```

으로 수정하면 됩니다.

지금 당장은 서버에서 가져오는 것도 아니라서 나중에 수정해도 될듯 합니다.

2023-11-15 10:11 UTC, kbs1027 approved these changes

2023-11-15 10:18 UTC, mun-kyeong commented on src/page/Recruit/RecruitDescription.jsx
> +        <h2 className="text-base text-[#FFBD00] mb-10">모집기간 : 2023.08.15 ~ 2023.08.31</h2>
이런 디테일함,, 말도 안되네요 도균님

2023-11-15 10:20 UTC, kbs1027 commented on src/page/Recruit/RecruitDescription.jsx
> +        <h2 className="text-base text-[#FFBD00] mb-10">모집기간 : 2023.08.15 ~ 2023.08.31</h2>
와 레전드 이걸보네

2023-11-16 06:13 UTC, merged