Feature/메인화면 information 레이아웃 설정 #30
Untoc-Web-Develop/Untoc-Front pull request #31
Opened 2023-11-16 12:34 UTC by mun-kyeong

## 관련이슈

-  #30

## 요약

main화면을 구성하는 총 4 파트 ( info / activity / history / recruit ) 중 첫 화면입니다. 

## 상세

- 디자인적 요소를 더 추가하고 싶엇는데 우선 화면 만들고 보이는게 우선이라 생각해서 여기서 마무리하고 PR 날립니다1
- **css파일 삭제했습니다!**

## 리뷰안내

- 리뷰 예상 소요 시간
 10분
 
- 참고사항 
 그 main 페이지도 상단 네비게이션바 기본값으로 고정해서 넣을까요?
 저번에 main 페이지에서만 헤더 색 바꿀 수 있게 해본다고 했던 것 같은데 
 급하면 우선 이대로 둬도 괜찮을 것 같아서 말해봅니다. 

- 프리뷰이미지
![main화면](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/96461334/a1635f18-4796-421f-8c9f-f4c7218eddbe)

2023-11-17 10:52 UTC, hdh4952 commented on src/css/main/MainInfo.css
> +
css파일 대신 tailwind로 바꿔주세요

2023-11-17 11:00 UTC, hdh4952 requested changes

2023-11-17 11:00 UTC, hdh4952 commented on src/css/main/MainInfo.css
> +}
css파일 대신 tailwind로 바꿔주세요

2023-11-17 11:00 UTC, hdh4952 commented on src/page/Main/MainInfo/MainInfo.jsx
> +      }}
tailwind로 변경해주세요

2023-11-20 14:31 UTC, hdh4952 approved these changes
좋습니다~

2023-11-20 14:31 UTC, hdh4952 commented on src/page/Main/MainInfo/MainInfo.jsx
> +  }, []);
이 부분 component로 만들어서 css animation으로 만들 수 있지 않을까요?

2023-11-20 14:33 UTC, mun-kyeong commented on src/page/Main/MainInfo/MainInfo.jsx
> +  }, []);
오 좋은데요 한번 @keyframe으로 만들어보겠습니다!

2023-11-20 15:19 UTC, kbs1027 approved these changes

2023-11-22 22:56 UTC, jasper200207 requested changes
자잘한 사항들이라 package.json 외에는 넘어가겠습니다.

package.json은 충돌나거나 나중에 다루기 제일 까다로운 부분이라 수정 부탁드립니다.

2023-11-22 22:56 UTC, jasper200207 commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
혹시 react-icons 만 사용하고 fortawesome은 사용할 예정이 없으시면 머지 전 삭제 부탁드립니다.

2023-11-22 22:56 UTC, jasper200207 commented on src/page/Main/Main.jsx
> +    </div>
의미없는 div의 경우 div대신 Fragment ( <> ) 사용하는 것도 좋아보입니다.

2023-11-22 22:56 UTC, jasper200207 commented on src/page/Main/MainInfo/MainInfo.jsx
> +  }, []);
이왕 keyframe 사용하는거 tailwindcss config 파일에 작성 부탁드립니다.
return에는 tailwind className만 남기는 게 좋을듯 해서요...

2023-11-22 22:56 UTC, jasper200207 commented on src/page/Main/MainInfo/MainInfo.jsx
> +      <div className="absolute top-[170px] right-[-100px] xl:w-[30em] xl:h-[30em] md:w-[20em] md:h-[20em] bg-white bg-opacity-40 backdrop-blur rounded-full" />
이부분 Circle 컴포넌트로 빼는게 좋을 듯 합니다.

size, top, bottom, left, right를 props로 받으면 좋을 듯 합니다.

2023-11-22 22:56 UTC, jasper200207 commented on src/page/Main/MainInfo/MainInfo.jsx
> +      <div className="absolute   xl:text-5xl md:text-4xl right-10 font-bold top-96 animate-fadeIn  duration-1000 ease-out ">
큰 영향은 없지만 스페이스바가 과하게 들어갔습니다.

absolute 뒤랑 fadeIn 뒤, 맨 위의 text-md 뒤, left-28 뒤 입니다.....

중간중간 className 맨뒤에 들어간 스페이스바도 보입니다...

2023-11-22 22:56 UTC, jasper200207 commented on src/page/Main/MainInfo/MainInfo.jsx
> +          탄소처럼 꼭 필요한 존재가 되자는 슬로건을 가지고 있습니다.
아직은 더미라 상관은 없으나 되도록이면 이런 줄글 줄바꿈은 <br/> 대신 \n 와 whitespace-pre-wrap 사용 부탁드립니다.

2023-11-22 22:56 UTC, jasper200207 commented on tailwind.config.js
> +      },
tailwind.config 활용 좋습니다!

2023-11-23 00:27 UTC, mun-kyeong commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
헉 그렇네요 생각을 못하고 있었다!! 수정하겠습니다 :)

2023-11-23 00:28 UTC, mun-kyeong commented on src/page/Main/Main.jsx
> +    </div>
아 의미가 없을 경우 그렇게도 사용 가능한거였군요..!! 수정하겠습니다~~ 감사합니다 :)

2023-11-23 00:33 UTC, mun-kyeong commented on src/page/Main/MainInfo/MainInfo.jsx
> +      <div className="absolute top-[170px] right-[-100px] xl:w-[30em] xl:h-[30em] md:w-[20em] md:h-[20em] bg-white bg-opacity-40 backdrop-blur rounded-full" />
넵 알겠습니다!! 
안그래도 보기가 넘 안좋아가지고 고민하고 있었는데 이왕 깔끔하게 만들꺼면 컴포넌트가 좋아보여요.
props size, 위치별로 받는거 좋은것 같습니다 :) 수정후 다시 PR올리겠습니닷

2023-11-23 00:35 UTC, mun-kyeong commented on src/page/Main/MainInfo/MainInfo.jsx
> +      <div className="absolute   xl:text-5xl md:text-4xl right-10 font-bold top-96 animate-fadeIn  duration-1000 ease-out ">
엌ㅋㅋㅋㅋㅋㅋ 이거 그 복붙하다보니 다들 안예쁘게 정렬되었나봐요 ㅋㅋㅋㅋㅋ 
아니 도균상 이렇게 섬세한거 캐치하는것도 진짜 능력인듯한데 진짜 너 대단한것같다
이런 디테일함이 너무 필요했어요 ㅜㅜㅜ 감사합니다

2023-11-23 00:35 UTC, mun-kyeong commented on src/page/Main/MainInfo/MainInfo.jsx
> +          탄소처럼 꼭 필요한 존재가 되자는 슬로건을 가지고 있습니다.
아 그때 안쓰는게 좋다고 하셨던거 기억나는군요..!! "\n" 으로 바꿔서 쓰겠습니당 ㅎㅎ

2024-01-01 11:29 UTC, jasper200207 approved these changes
mui 설치 때문에 일단 머지 합니다.
@hdh4952 님이 fortawesom 삭제해주시로 했습니다

2024-01-01 11:29 UTC, merged