feat : 회원가입 페이지
Untoc-Web-Develop/Untoc-Front pull request #37
Opened 2023-11-20 11:50 UTC by jimini1026

## 관련이슈

- #8

## 요약

회원가입 페이지 입니다

## 상세

- 기능구현 미완성

## 리뷰안내

- 리뷰 예상 소요 시간 : 10분
- 프리뷰이미지
![캡처](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/ae9e72f2-df8e-4e50-8f59-1e1ec63bbfd3)

2023-11-21 06:31 UTC, kbs1027 reviewed
tailwind.css사용해서 색을 사용해주세요 그리고 고정크기보다는 화면비율로 맞춰주세요

2023-11-21 06:31 UTC, kbs1027 commented on src/page/Register/Register.jsx
> +        <h1 className="text-5xl text-yellow-300 font-semibold text-center m-8">UntoC</h1>
색은 tailwind.css사용해주세요

2023-11-21 06:31 UTC, kbs1027 commented on src/page/Register/Register.jsx
> +                className="w-80 h-10 rounded-full border border-gray-300 text-sm p-3"
고정된 것보다는 화면비율로 바꾸는게 좋지 않을까요?

2023-11-21 11:39 UTC, mun-kyeong reviewed
수고하셨습니다!! 화면이 완성되어 든든하네요 :)
몇 가지 수정사항 comment 작성했으니 확인부탁드려요 :)
잘 이해가 안되거나 모르겠는 부분 편하게 질문하셔도 됩니다.

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +                className="w-80 h-10 rounded-full border border-gray-300 text-sm p-3"
이부분 높이를 좀 여유롭게 잡아주셨으면 합니다!! h-12나 h-14 정도? 
figma 화면 참고하셔서 조금 여백이 여유로웠으면 해요!
그리고 tailwind.config.js 파일 확인해보시면  borderColor 라는 색이 따로 지정되어 있어요!
taliwind.config.js 파일 확인해보고 만약 color 변수 설정이 업데이트 안되어있다면 pull 한번 받고 수정하시면 될 것 같습니다 :)

border-gray-300 이 부분을 border-borderColor 이런 식으로 사용하시면 돼요.
위에 범수님이 말씀하신 부분과 같은 부분입니다! 
text-placeHolder 속성도 부탁드릴께요 :)

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +                className="w-80 h-10 rounded-full border border-gray-300 text-sm p-3"
음 화면 비율로 바꾸면 반응형 페이지 만들때 가로/세로 너비가 같이 줄어들 것 같은데 고정 너비가 맞지 않을까요? 
이거 너비 고정해두면 반응형 페이지 사실 고려할필요 없이 mx-auto 쓰면 그냥 자동으로 여백 너비만 조정되어서 줄어들 것 같은데
@kbs1027 확인 한번 부탁해요!

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +      return '이름 형식이 올바르지 않습니다';
앗 지금 이 부분이 출력되고 있는 것 같은데 원래는 "본명으로 기입해주세요" 라는 글자가 default로 나와야 할 것 같습니다 :)

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +                className="w-80 h-10 rounded-full border border-gray-300 text-sm p-3"
figma 화면 확인해보시면 여기에는 border 속성 안넣어도 될 것 같습니다!

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +            className="w-80 h-10 rounded-full border border-gray-300 text-gray-400 text-xs absolute"
여기는 border 속성 없어도 될 것 같고 대신에 bg-borderColor 으로 배경화면 색 바꿔주시고 text-white font-bold 속성 추가해주세요!  그리고 여기에 absolute가 추가된 이유가 있나요?

2023-11-21 11:39 UTC, mun-kyeong commented on src/page/Register/Register.jsx
> +            <Link to="/login" className="text-yellow-300 ml-3">
마찬가지로 text-yellowPoint 속성 사용해주세요! tailwind.config.js 파일 안에 색상 커스텀으로 만들어두었습니다 :)

2023-11-22 22:44 UTC, jasper200207 approved these changes
추후에 react-hook-form 사용하면서 많이 바뀔듯 하기도 하고 큰 문제가 없는 사항들이라 일단 approve 하겠습니다.

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +              }`}
tailwindcss에 ```disable:``` 라는 문법이 있습니다.
```bg-yelloPoint disable:bg-borderColor``` 로 사용하면 훨씬 깔끔할거 같습니다.

참고로 ```disable:``` 은 disable 상태일때만 적용되는 className을 넣는 겁니다

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +              username === '' || studentnumber === '' || phonenumber === '' || password === '' || confirmpassword === ''
일단, disable 처리 해둔거 좋습니다!

username === ''이 정확하게 비교해서 좋지만 코드가 너무 길어진거 같네요.
```!username || !studentnumber || !phonenumber || !password || !confirmpassword```
로 작성하는 방법도 좋을 듯 합니다.

빈문자열 ('')은 어차피 false와 같은 값으로 취급되기에 같은 결과가 나옵니다.
굳이 차이점을 두자면 ===로 비교하면 undefined와 null일때 값이 있는걸로 인식되어 문제가 생길 수 있습니다.

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +        <h1 className="text-5xl text-yellow-300 font-semibold text-center m-8">UntoC</h1>
부가 설명을 하자면 ```text-yellowPoint``` 를 사용하면 좋을 듯 합니다.

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +    <div className="grid place-items-center mx-auto my-auto h-content">
grid 사용한건 좋지만 밑에 form 태그만 있어 별 효과가 없을 듯 하네요 이런 경우에는 ```flex``` 사용해도 좋고 가로로 배치되어 불편하면 ```flex flex-col``` 을 사용하면 됩니다.

사실, flex가 은근 만능인게 margin, padding, w-full 등등이 안먹힐때 flex 넣으면 왠만해선 됩니다....

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +  };
비밀번호 확인 기능 넣은거 좋습니다!

2023-11-22 22:44 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +              </button>
absolute로 띄울려는 시도는 좋으나 비효율 적일 듯 합니다.

input의 className을 div에 적용시키고 button을 div에 넣는것도 좋아보입니다.

2023-11-23 04:47 UTC, hdh4952 approved these changes
다음에 useForm 배울 때 같이 배워서 써먹으면 좋을 것 같네요. 좋습니다~!

2023-11-23 09:11 UTC, kbs1027 requested changes
tailwindcss 적용 부탁드립니다

2023-11-24 04:50 UTC, jimini1026 commented on src/page/Register/Register.jsx
> +        <h1 className="text-5xl text-yellow-300 font-semibold text-center m-8">UntoC</h1>
tailwindcss 수정 빠진 곳이 있네요... 다시 수정하겠습니다

2023-11-24 04:58 UTC, jimini1026 commented on src/page/Register/Register.jsx
> +              </button>
변경하려고는 하고 있는데 디자인이 뭔가 엉성하게 되고 있어서... 일단 다른 나머지 부분들은 수정해서 다시 올리고 div에 button 넣도록 해볼게요

2023-11-27 11:03 UTC, kbs1027 commented on src/page/Register/Register.jsx
> +                className="w-80 h-10 rounded-full border border-gray-300 text-sm p-3"
비율은 그대로 가도 될거같네요

2023-11-27 11:18 UTC, kbs1027 approved these changes
수고하셨습니다~

2023-11-27 20:27 UTC, jasper200207 commented on src/page/Register/Register.jsx
> +              </button>
``` html
<div className="w-80 h-12 rounded-full border-borderColor border px-1 place-items-center flex focus-within:outline">
    <input
        className="w-60 rounded-l-full text-sm p-2 outline-none"
        type="email"
        id="email" 
        placeholder="UntoC@pusan.ac.kr"
        required
    />
    <button
        className="w-20 h-10 rounded-full border border-borderColor text-placeHolder text-xs bg-white"
        type="submit"
    >
        확인
    </button>
</div>
```

참고용 입니다. 사실 absolute도 나쁜건 아닌데 flex로 하는편이 크기 조절이나 반응형 처리가 편할듯 했습니다.

2023-12-26 10:38 UTC, merged