Feature/신입회원 모집 페이지 관리자 #38
Untoc-Web-Develop/Untoc-Front pull request #40
Opened 2023-11-23 06:57 UTC by hdh4952

## 관련이슈

- #38 

## 요약

신입 회원 모집 페이지를 관리자 권한으로 접속했을 때 보이는 페이지를 추가했습니다.

## 상세

- 관리자 화면 추가했습니다.
- 목록이 화면을 넘어갈 경우 스크롤 시 좌측 모집 설명란이 따라가도록 변경했습니다.
- 목록 추가 및 삭제 기능을 추가했습니다.
- 목록 사항이 변경되면 제출 버튼 비활성화 기능을 추가했습니다.

## 리뷰안내

- 리뷰 예상 소요 시간 : 20분
- 참고사항
  - 관리자 화면을 보기 위해서는 권한이 admin으로 설정되어야 합니다.
  - 기본 항목을 하드코딩했습니다. 추후에 api 추가와 같이 변경할 예정입니다.
  - 신입회원 모집 관련 api 논의가 필요할 것 같습니다.
- 프리뷰이미지
<img width="1280" alt="image" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/29ed907d-d215-4b1f-83f9-d2c6a938ba5b">
<img width="1280" alt="image" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/2971906b-b862-42cb-98db-1fbe773cc84f">

2023-11-23 08:00 UTC, jasper200207 requested changes
역시 작업속도가 빠르네요

코멘트 보신후 답변 혹은 반영 부탁드립니다.

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitDescription.jsx
> +    <div className="sticky top-0 flex flex-col items-center justify-start w-full h-full px-12 text-sm font-normal">
sticky 중복으로 들어갔습니다. Recruit의 sticky는 없어도 될듯 하네요

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +                disabled={role === 'admin'}
admin 체크 좋습니다.

하지만, Header랑 같이 만든 useRoleCheck 사용하는 것도 좋아보입니다. 역할 비교 로직이 복잡해졌을 때 같이 바꿀수 있어 좋습니다.

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +          />
input의 button 보다는 button을 사용하는게 알아보기 좋을듯 합니다

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +  const [originalApplyQuestions, setOriginalApplyQuestions] = useState([]);
두개 차이가 뭔가요...?

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitFormAdmin.jsx
> +                    ]);
나름 괜찮은 방식이긴 하나

```
setApplyQuestions((prev) => [
                      ...prev.slice(0, idx),
                      { id, question: e.target.value, content },
                      ...prev.slice(idx + 1),
                    ])
```

로 사용하는 건 어떨까요? set 에서 자기자신을 불러올때는 되도록 이면 함수로 해주는게 좋습니다. 빠르게 바뀔경우 반영이 안될 수 있습니다.

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitFormAdmin.jsx
> +        return (
이렇게 하는 대신
```
{applyQuestions.map(({id, question, content}, idx) => (<div ...
```
로 하는건 어떨까요? return 안에 return이 있는 것 보다 가독성이 좋아질듯 합니다.
아니면 id로 사용하는 대신 applyQuestion.id로 사용해도 좋을듯 하네요

2023-11-23 08:00 UTC, jasper200207 commented on src/page/Recruit/RecruitFormAdmin.jsx
> +          <div className="w-full h-32 mb-8">
추가로 map을 사용했을 땐 key 입력 부탁드립니다. key는 바뀌지 않는 선에서 고유값으로 넣으면 됩니다. 가장 좋은 방식은 벡엔드에서 가져온 id값을 넣는 겁니다. 이경우는 그냥 id 넣으면 좋을 듯 합니다.

2023-11-23 08:08 UTC, hdh4952 commented on src/page/Recruit/RecruitForm.jsx
> +  const [originalApplyQuestions, setOriginalApplyQuestions] = useState([]);
목록이 수정되었을 경우, 기존의 목록과 비교할 수 있도록 원본 목록을 만들었습니다.
다시 생각해보니 목록 비교보다는 변경됐는지만 확인하면 좀 더 편해질 것 같네요. 수정하겠습니다.

2023-11-24 06:09 UTC, jasper200207 approved these changes
수고하셨습니다. 자잘한거만 남아서 코멘트 한번 확인만 해주세요

2023-11-24 06:09 UTC, jasper200207 commented on src/page/Recruit/RecruitDescription.jsx
> +    <div className="top-0 flex flex-col items-center justify-start w-full h-full px-12 text-sm font-normal">
flex는 top-0 효과 없는걸로 알고있습니다

2023-11-24 06:09 UTC, jasper200207 commented on src/page/Recruit/RecruitForm.jsx
> +          )}
OnlyLogin 컴포넌트 사용하면 좋을 듯 한데 제가 반대일때만 렌더링을 안넣었네요...
나중에 useRoleCheck 수정하고 나면 여기도 수정 부탁드립니다. 아마도 OnlyLogin에 elseComponent prop 넣을듯 싶네요

2023-11-27 11:15 UTC, kbs1027 approved these changes
수고하셨습니다!

2023-11-28 03:48 UTC, mun-kyeong requested changes
혹시 저번에는 그냥 border로 사용을 하셨던 것 같은데 전체적으로 border-2로 두꺼워진듯한 느낌이 들어서요...!! 
혹시 border를 두껍게 하신 이유가 있을까요?
개인적으로는 얇은 테두리가 예쁘다고 생각을 해서,,,
테두리가 잘 안보였다거나 아님 디자인적으로 수정이 필요했다고 생각이 되어서 바꾸신거였나요?

기술적인 부분은 저번에 도균님께서 봐주셨던 것 같아서 저는 디자인 쪽으로 코멘트를 조금 더 붙였습니다!

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/Recruit.jsx
> +    <div className="flex justify-center w-screen overflow-x-hidden h-content align-center bg-grayLight">
이거 bg-grayLight가 tailwind에서 선언이 잘못되어있어서 적용이 안되어있는 것 같은데 후에 첫글자는 소문자로 수정 전부 해놓겠습니다!

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
>              <label htmlFor="studentId" className="w-60">
그리고 w-60으로 사이즈를 고정해두면 가로사이즈가 늘어났을때 학번-이름 두개 사이 공백이 보이고 
가로 사이즈를 극단으로 줄였을때 두개 input 겹쳐보입니다!!

사이즈 줄였을때 겹쳐보이는건 나중에 반응형으로 만들때 수정하면 되겠지만 우선 화면이 큰 컴퓨터로 해당 페이지 보니까 학번-이름 사이 공백이 이상하게 띄워져있어요

이거 학번이랑 이름 w사이즈를 w-2/5 이렇게 비율로 조정하는건 어떤가요? 
그러면 고정사이즈가 아니라서 너비에 따라 자동 % 조절이 될것같습니당

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
>              <label htmlFor="name" className="w-60">
이부분도 학번 이랑 마찬가지로 수정부탁드려요!
밑에 부분은 w-full로 설정해두셔서 자동으로 사이즈 조절 됩니당 :)

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +                className="w-full p-1 border-2 border-borderColor focus:outline-none focus:border-grayDark"
그리고 사소한걸수도 있겠지만 px-2 나 px-3으로 가로패딩 조금 더 넣어주셨음 합니당 :)
그리고 border 두께가 두꺼워진 이유를 물어봐도 되나용?

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitFormUser.jsx
> +                className="w-full p-1 border-2 resize-none h-2/3 border-borderColor focus:outline-none focus:border-grayDark text-grayDark"
여기도 px-2나 px-3으로 가로 여백 조금 더 들어갔으면 좋을것같아요!

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +                    // @Todo: save applyQuestions for admin
오잉 이 어노테이션(?) 은 어떻게 쓰는건가요? 
react에서도 @ 어노테이션이 사용가능한지 몰랐네

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +          {isLogin ? (
오 이런식으로 필요한 부분만 바꿔서 렌더링 하는거 너무 좋은것같습니다! 깔끔하네요

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitFormAdmin.jsx
> +        <CiSquarePlus size={32} className="mr-2 text-grayDark" />
음 이부분도 placeHolder색이면 조금 더 좋을것같네요! 
피그마에는 grayDark로 되어있긴힌데 연한색이면 조금 더 자연스러울 것 같다는 생각이 방금 들엇습니당 :)

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitFormAdmin.jsx
> +                  className="relative w-9/12 mb-3 border-b-2 border-borderColor focus:outline-none focus:border-b-grayDark text-grayDark"
여기부분도 px-2나 px-3으로 널널했으면 좋겠습니다..!

2023-11-28 03:48 UTC, mun-kyeong commented on src/page/Recruit/RecruitFormAdmin.jsx
> +                className="w-full p-1 border-2 resize-none h-2/3 border-borderColor focus:outline-none focus:border-grayDark text-grayDark"
엉엉 자꾸 사소한 부분 건드는 것 같아서 미안하지만 ㅜㅜ 
디자인에 있어서 가장 중요한게 여백이여서요,,
여백이 널널해야 보기가 좋아보입니다,,,,
여기도,, padding 속성 조금 더 널널하게 부탁드려요ㅜㅜ

2023-11-28 04:09 UTC, hdh4952 commented on src/page/Recruit/RecruitForm.jsx
>              <label htmlFor="studentId" className="w-60">
아마 이전에 5/12로 맞췄던 것 같은데 여백이 너무 큰 것 같아서 고정 사이즈로 변경한 것 같습니다. 다시 바꿔보고 정 안되면 비율 속성을 추가하겠습니다.

2023-11-28 04:11 UTC, hdh4952 commented on src/page/Recruit/RecruitForm.jsx
> +                className="w-full p-1 border-2 border-borderColor focus:outline-none focus:border-grayDark"
border가 잘 안보여서 변경한 것 같습니다. 두께 수정하고, padding값 늘리겠습니다.

2023-11-28 04:19 UTC, hdh4952 commented on src/page/Recruit/RecruitForm.jsx
> +                    // @Todo: save applyQuestions for admin
jsdoc 주석 다는 방법을 보고 따라한 건데 정확히 사용한 게 아닌 것 같네요. 주석 고급지게 달고 싶으면 한 번 찾아보세요 :)

2023-11-28 07:03 UTC, mun-kyeong approved these changes
좋아요~~ 어느정도 수정이 다 반영된것 같아서 approve 하겠습니다 :)
다음에는 혹시 여유가 된다면 수정이 완료된 화면으로 참고 이미지 부탁드릴께요
수고하셨습니다~~~~

2023-11-28 07:03 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +                disabled={isLogin}
오 어드민 계정에서는 수정이 필요한 부분이 아니여서 disabled처리하신거 맞으신가요?
아이디어 굉장히 좋네요 :)

2023-11-28 07:03 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
>              <label htmlFor="studentId" className="w-60">
아아 그럼 부탁드립니다!! 머싯다,, 한대희,,,

2023-11-28 07:03 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +                className="w-full p-1 border-2 border-borderColor focus:outline-none focus:border-grayDark"
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 밑에 내용 거의 중복이라 눈 이모지로 확인햇다고만 알려주세요. 감사합니다!!
만약 넘 안보인다 싶으면 [1.5px] <-- 되려나 모르겠지만 한번 추천드려요

2023-11-28 07:03 UTC, mun-kyeong commented on src/page/Recruit/RecruitForm.jsx
> +                    // @Todo: save applyQuestions for admin
아 주석이구나 저게 ㄷㄷㄷㄷ 미쳤네요 완전 꿀팁니다
나중에 시간나면 한번 찾아봐야겠습니다

2023-11-28 07:05 UTC, merged