Feature/게시판 페이지 #6
Untoc-Web-Develop/Untoc-Front pull request #44
Opened 2023-11-23 08:48 UTC by kbs1027

## 관련이슈

- #41 
- #42 
- #43 

## 요약
- tailwindcss 색상 추가
- BoardPage Router 분리후 AppRouter와 연결
- BoardWrite Page 틀 완성 
## 상세
- textarea는 Markdown editor가 정해질 시 바꿀예정
- 이미지 추가시 이미지 변경 예정
- 기능구현은 아직 미완성

## 작업에 대한 상세 정보
- tailwindcss "#D1D5DB", "#9CA3AF" 색상 추가
- BoardPage Router를 BoardWrite, Board, BoardView로 분리
- BoardWrite Page 틀을 완성

## 리뷰안내

- 15분 소요예정
- tailwindcss에 색상 추가한거 한번 더 확인 부탁드림
<img width="1728" alt="스크린샷 2023-11-23 오후 5 19 25" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/116559420/28fd6a98-c0a0-44f3-891e-70ad2e8dcfa2">

2023-11-24 05:02 UTC, hdh4952 approved these changes
수고하셨습니다

2023-11-24 05:02 UTC, hdh4952 commented on src/page/BoardWrite/BoardWrite.jsx
> +    setIsMustRead(!isMustRead); // Toggle checkbox state
setIsMustRead((prev) => !prev); 로 교체하면 더 좋아질 것 같네요.

2023-11-26 07:34 UTC, jimini1026 approved these changes
좋아요

2023-11-26 08:39 UTC, jasper200207 requested changes
다음 PR은 리뷰어랑 담당자 등 지정 해주세요..
그래야 알림이 옵니다....

2023-11-26 08:39 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +    setIsMustRead(!isMustRead); // Toggle checkbox state
이건 나름 수정이 필요한 사항이라 Reject로 걸어두겠습니다.

2023-11-27 20:43 UTC, jasper200207 requested changes

2023-11-27 20:43 UTC, jasper200207 commented on src/routes/BoardRouter.jsx
> +import BoardView from 'page/BoardView/BoardView';
지금 BoardView 파일이 없는 듯 한데 빈 컴포넌트로 추가하거나 Route에서 빼주시면 좋을듯합니다. 확인할때 오류가 납니다...
주석처리도 괜찮습니다.

2023-11-27 20:43 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +              </h2>
이부분 특수기호 사용보다는 `<ul>, <li>` 태그를 사용하는 편이 알아보기 좋아보입니다.
추가적으로 `<h2>, <h1>` 등의 태그는 tailwindcss 적용시 별도의 기본 스타일이 없어 굳이 안쓰시고 `<p>` 태그로 통일해도 됩니다. 아니면 mui Typograph로 통일하는 것도 좋을 듯 하네요.

아래는 예제 코드입니다. 참고하시면 됩니다.
```html
<ul className="list-disc">
    <li>
        공지 게시글은 <span className="text-yellowPoint">관리자 이상의 등급</span>만 작성 가능합니다.
    </li>
    <li>
        공지 게시글을 <span className="text-yellowPoint">필독으로 지정하여 상단에 고정</span>해둘 수 있으나, 지난 게시글은 관리를 통해 고정해제가 필요합니다.
    </li>
</ul>
```

2023-11-27 20:43 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +              className="bg-yellowPoint w-1/12 text-white py-1 text-sm  rounded hover:bg-white hover:text-black border border-yellowPoint"
```suggestion
              className="bg-yellowPoint w-1/12 text-white py-1 text-sm rounded hover:bg-white hover:text-black border border-yellowPoint"
```

2023-11-27 20:43 UTC, jasper200207 commented on src/routes/BoardRouter.jsx
> +      <Route path="boardwrite" element={<BoardWrite />} />
큰 상관은 없는데 `boardview boardwrite` 대신 `view write`만 사용하는 건 어떨까요?

앞에 board가 붙어서 경로가 `/board/boardview`로 `board`가 중복이 됩니다.

2023-11-28 03:13 UTC, kbs1027 commented on src/routes/BoardRouter.jsx
> +import BoardView from 'page/BoardView/BoardView';
아 넵 알겠습니다

2023-11-28 03:13 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +              </h2>
넵

2023-11-28 03:14 UTC, kbs1027 commented on src/routes/BoardRouter.jsx
> +      <Route path="boardwrite" element={<BoardWrite />} />
알겠습니다

2023-11-28 03:15 UTC, kbs1027 commented on src/routes/BoardRouter.jsx
> +      <Route path="boardwrite" element={<BoardWrite />} />
@jasper200207 혹시 view 만들던게 있는데 그냥 그대로 올려도 될까요?? 아직 완성은 안되었는데 그냥 빈 컴포넌트로 할까요?

2023-11-28 06:01 UTC, hdh4952 approved these changes
확인했습니다~

2023-11-28 06:58 UTC, mun-kyeong requested changes
뭔가 디자인적으로 계속 보이니까 말하게 됩네요 ㅋㅌㅋ투ㅜㅠㅠ
리젝트 한 이유는 figma.config.js 파일때문에 그렇습니다!!
혹시 가능하다면 여기 merge가 더 빠를 것 같아서 맨 앞글자 소문자로 통일 가능할까요?

2023-11-28 06:58 UTC, mun-kyeong commented on tailwind.config.js
>          GrayLight: '#F8F8F9',
여기서부터 맨앞글자만 소문자로 변경부탁드립니다!

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +              <img src={RecruitImg} alt="recruitImg" className="h-5 w-5" />
이부분 이미지로 사용하지 말고 아이콘으로 대체해도 괜찮을 것 같은데 
[react-icons](https://react-icons.github.io/react-icons/search/#q=bulb)
아이콘 이걸로 통일하려고 하거든요. 

react-icon 이거 설치방법 npm installl 하고 위에 import 한담에 <> 컴포넌트 바로 복사해서 사용하심 됩니다.
이미지보단 아이콘이 좋을 것 같아요

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +        <hr className="border-2 border-yellowPoint" />
border 로 변경부탁드립니다~~ border-2는 너무 두꺼운 것 같아요.
> border의 경우 default로 border-1을 의미합니다

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +          <div className="m-7 w-1/2 mx-auto">
mx-7 my-10 정도로 `작성 가이드라인` 이 들어가는 부분 세로 여백이 조금 더 많았으면 합니다. (figma 참고)
굳이 my-10일필요는 없지만 지금보다는 조금 더 여유롭게 잡아주세요!

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +        <div className="w-2/3 mx-auto mt-3 h-2/3">
노란색 구분선 이후에는 mt-7이나 mt-10 정도로 마찬가지로 여백 여유롭게 부탁드립니다!
(숫자로 봐서는 얼마나 잡아야 할지 감이 잘 안와서,, figma 확인하시면서 대충 비슷하게 보이는 정도의 여백이면 좋아요)

> 여백을 계속 잡는 이유가,, 디자인에 있어서는 여백이 숨통같은거라 널널할수록 좋습니다.
너무 자잘한것까지 건드는게 아닌가 싶지만,, 그래도 예뻐보이는게 좋아서 코멘트 하나씩 남깁니다

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +            <div className="text-xs text-grayPoint400">
이거 placeHolder 색으로 사용가능합니다!! 
색 잘 모르겠으면 figma에 들어가서 사용한 색 확인하면 돼요

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +                  className="w-full p-2 border-0 border-b-2 border-solid border-grayPoint300 text-grayDark"
마찬가지로 placeHolder 색으로 grayPoint300 대체가능합니다!!
그리고 mb-5나 mb-7정도로 제목 필드랑 본문 필드랑 여유로운 여백 부탁드려요 (figma 참고)

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +              className="bg-white w-1/12 border border-grayPoint300 text-black py-1 text-sm rounded hover:bg-yellowPoint hover:text-white hover:border-yellowPoint"
여기도 border-color 라는 색으로 대체가능합니다!! 
figma에서 만든 색으로 웬만하면 대체 가능해서 확인 부탁드려요 :)

2023-11-28 06:58 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +    <div className="h-screen">
여기 전체적으로 bg-grayLight 속성 필요한 것 같은데 수정 부탁드립니다아ㅏ

2023-11-28 06:58 UTC, mun-kyeong commented on tailwind.config.js
> +        grayPoint400: '#9CA3AF',
이부분 근데 figma에서 따로 만든 부분이 아닌 것 같은데
웬만하면 이미 만들어져있는 색으로 대체 가능한 것 같아서 삭제하는게 어떤가요? **(코멘트 참고)**
헷갈릴수도 있을 것 같슴돠

@kbs1027 @jasper200207 @hdh4952 @jimini1026  @parkqjunseo  다들 의견은 어떠신가요
추가가 필요하면 놔둬도 괜찮을 것 같아요

2023-11-28 07:02 UTC, hdh4952 commented on tailwind.config.js
> +        grayPoint400: '#9CA3AF',
색상을 늘리기보단 통일할 수 있으면 통일하는 게 좀 더 보기 편할 것 같습니다!

2023-11-28 07:03 UTC, kbs1027 commented on tailwind.config.js
> +        grayPoint400: '#9CA3AF',
이게 피그마에서 똑같은 색을 찾다보니깐 이부분을 안사용하면 색이 이상해집니다.

2023-11-28 09:15 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +              <img src={RecruitImg} alt="recruitImg" className="h-5 w-5" />
넵

2023-11-28 09:22 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +        <hr className="border-2 border-yellowPoint" />
<img width="1027" alt="스크린샷 2023-11-28 오후 6 21 12" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/116559420/6ffd2fed-b21b-4058-9b70-63e8fa40d837">
border-1로 하면 너무 얇아서 figma에도 2라고 되어 있어서 2로 그냥 고정시키는게 맞을거 같습니다

2023-11-28 09:25 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +          <div className="m-7 w-1/2 mx-auto">
어차피 중앙정렬이라 mx는 건들필요가 없을 것 같아서 my만 10정도로 바꾸겠습니다

2023-11-28 09:28 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +        <div className="w-2/3 mx-auto mt-3 h-2/3">
네 알겠습니다

2023-11-28 09:46 UTC, jasper200207 requested changes

2023-11-28 09:46 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +              <img src={RecruitImg} alt="recruitImg" className="h-5 w-5" />
이거 일단 설치 진행하지 않아도 될듯 합니다. 괜히 따로 설치하면 충돌의 위험이 있어서....

2023-11-28 09:46 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +              </p>
`<ul>, <li>` 도 적용 부탁드립니다

2023-11-29 01:05 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +        <hr className="border-2 border-yellowPoint" />
앗 알겠습니다!! 그럼 border-2로 진행하면 될것같습니당

2023-11-29 01:05 UTC, mun-kyeong commented on src/page/BoardWrite/BoardWrite.jsx
> +          <div className="m-7 w-1/2 mx-auto">
넵 !! 감사합니다

2023-11-29 01:07 UTC, mun-kyeong commented on tailwind.config.js
> +        grayPoint400: '#9CA3AF',
엇 앞서 코멘트 달았던 부분 색으로 대체해도 이상하게 보이나요?

2023-12-04 01:51 UTC, kbs1027 commented on src/page/BoardWrite/BoardWrite.jsx
> +              </p>
넵

2023-12-04 01:51 UTC, kbs1027 commented on tailwind.config.js
> +        grayPoint400: '#9CA3AF',
대체 하여서 바꿧습니다 ㅎ

2023-12-04 02:43 UTC, jasper200207 requested changes

2023-12-04 02:43 UTC, jasper200207 commented on src/page/BoardWrite/BoardWrite.jsx
> +              </ul>
이 부분 `&bull;` 대신 `<ul>` 태그에 ` className="list-disc"` 추가해주세요.
그럼 닷은 알아서 추가될겁니다.

2023-12-04 10:24 UTC, jasper200207 approved these changes
수고하셨습니다

2023-12-26 11:19 UTC, mun-kyeong approved these changes

2023-12-26 11:20 UTC, merged