Feature/메인화면 activity 레이아웃 설정 #32
Untoc-Web-Develop/Untoc-Front pull request #45
Opened 2023-11-25 06:52 UTC by mun-kyeong

## 관련이슈

-Feature/메인화면 activity 레이아웃 설정 #32

## 요약

main화면을 구성하는 4 파트중 activity 에 해당하는 두번째 화면입니다. 
teamInfoCard는 자주 사용될듯 싶어 공통 컴포넌트에 집어넣었습니다

## 상세

- 가로 무한 스크롤을 어떻게 구현해야할지 잘 모르겠어서 우선 tailwind의 slider속성을 사용해서 임시로 움직이는 것 같이 보이긴 하는데 이거 수정 필요해요.
- 가로 무한 스크롤을 구현할만한 좋은 아이디어 있으면 추천받습니다.
- 이미지랑 text는 어차피 나중에 가져와야 하는 값이라고 생각해서 index를 구분할 수 있는 임의의 값을 사용했고 이미지는 아무거나 사용햇어요
<br/>

- TeamInfoCard 공통 컴포넌트로 만든거 확인부탁드립니닷
- 밑에 사진이랑 글자랑 구분하려고 글자 부분만 **임시로** 붉은색 배경처리 햇습니다

## 리뷰안내

- 15분
-  참고사항
- 하나의 화면을 브랜치별로 나눠서 작업하는바람에 main화면을 병합할때 충돌이 일어날수도 있을 것 같은데 그부분은 제가 추후에 pull받고 다시 PR 올려서 충돌 해결하겠습니다
- 프리뷰이미지
![image](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/96461334/89b8776a-4474-438a-a8c4-1f40ef22eabb)

2023-11-25 15:11 UTC, jasper200207 requested changes
지금 같은 경우에는 PR에 관련 이슈에 #31 추가후 선행 리뷰 부탁드린다고 하면 됩니다.
그리고 #31 머지 이후에 충돌하면서 이 PR에 커밋하나 추가하면 될듯 하네요. 일단 앞에 PR이 먼저 머지되어야 할듯하여 머지 막는 용도로 Reject하겠습니다.

추가로 className 중간중간에 띄어쓰기 들어가 있는 걸 봤는데 해당 부분은 다음 회의때 tailwindcss 정렬 같이 적용하고 나면 고쳐질듯 해서 큰 문제는 없을듯 합니다.

2023-11-25 15:11 UTC, jasper200207 commented on src/page/Main/MainActivity/MainActivity.jsx
> +  const titles = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'];
큰 상관은 없지만 이런 테스트 데이터의 경우에는 컴포넌트 밖으로 빼주는게 좋습니다.
컴포넌트 안에 있으면 다시 렌더링 될때마다 만들어지기 때문에...

2023-11-25 15:11 UTC, jasper200207 commented on src/page/Main/MainActivity/MainActivity.jsx
> +        </Button>
button(html) 사용하는 사람이랑 Button(mui) 사용하는 사람이 나누어지는 듯 한데 이건 다음 회의때 통일하면 좋을 듯 하네요.

1. button 사용 (html)
2. Button 사용 (mui)
3. 공통 컴포넌트 StandardButton 제작

으로 나누어질 듯 합니다. 3으로 하게 되면 mui 기반으로 만들듯 합니다.

2023-11-26 13:27 UTC, hdh4952 approved these changes
잘 짜신 것 같습니다!

2023-11-26 13:27 UTC, hdh4952 commented on src/components/TeamInfoCard/TeamInfoCard.jsx
> +        <CardContent className="bg-red-200 !px-4 !py-2 ">
tailwind class명 앞에 '!'는 어떤 효과가 생기나요?

2023-11-27 11:11 UTC, kbs1027 requested changes

2023-11-27 11:11 UTC, kbs1027 commented on src/components/TeamInfoCard/TeamInfoCard.jsx
> +        <CardContent className="bg-red-200 !px-4 !py-2 ">
@hdh4952 tailwind.css에서 ! 기호를 클래스 앞에 붙이는 건 스타일의 우선순위를 강제로 높이는 것을 의미 한다고 하네요 @mun-kyeong 여기서는 우선 순위가 필요없는 것 같으니 코드 전체적으로 생각하여 !를 삭제해주시는게 코드 일관성에 맞을 것 같습니다

2023-11-27 20:30 UTC, jasper200207 commented on src/components/TeamInfoCard/TeamInfoCard.jsx
> +        <CardContent className="bg-red-200 !px-4 !py-2 ">
@kbs1027 ! 넣는게 맞습니다. 해당 컴포넌트는 mui에서 가져온거라 tailwind가 후순위로 밀리는 경우가 있습니다. 대표적인게 margin, padding, width, height 등인데 이경우는 ! 로 tailwindcss의 우선순위를 높이거나 props로 주는 선택지가 있습니다.

개인적으로는 tailwind 단위 통일이 편해서 ! 사용을 추천합니다

2023-12-26 11:19 UTC, kbs1027 approved these changes
수고하셨습니다

2024-01-01 11:30 UTC, jasper200207 approved these changes
👍

2024-02-13 12:49 UTC, jasper200207 requested changes
😢

2024-03-03 06:55 UTC, jimini1026 approved these changes
👍

2024-03-03 11:47 UTC, parkqjunseo approved these changes

2024-03-04 13:33 UTC, jasper200207 approved these changes
👍

2024-03-05 13:28 UTC, merged