Feature/공용 모달 #53
Untoc-Web-Develop/Untoc-Front pull request #54
Opened 2023-12-06 07:25 UTC by hdh4952

## 관련이슈

- #53 

## 요약

Modal, AlertModal, ConfirmModal 제작

## 상세

- AlertModal과 ConfirmModal 모두 Modal을 통해 구현
- outsideClose props를 통해 모달 바깥영역 클릭시 닫힘 기능 구현
- ConfirmModal의 confirmEvent props를 통해 실행할 함수 부여 가능

## 리뷰안내

- 리뷰 예상 소요 시간: 15분
- 프리뷰이미지

Modal
<img width="916" alt="스크린샷 2023-12-06 161815" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/6a3fd31d-7ddc-492c-bd06-627ecd73a7ba">

AlertModal
<img width="871" alt="스크린샷 2023-12-06 161655" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/09adf1cf-b970-44b7-8220-8c0002619a93">

ConfirmModal
<img width="873" alt="스크린샷 2023-12-06 161527" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/63997481/34c5ed8f-b4cf-404c-8c86-dd235c0d6bd0">

2023-12-08 14:03 UTC, jasper200207 requested changes
Modal.jsx 구현할때, useEffect나 useRef 등으로 구현하기 보다 가능한 기본으로 있는 onClick 을 통한 구현이 좋아보입니다. 코드 구조도 더 간단하고 불필요한 hook을 줄일 수 있습니다.

다만, 이런방식으로 구현하면 모달안을 클릭해도 바깥쪽 이벤트가 겹쳐지는 현상이 이러나게 됩니다. ( Event Bubbling 또는 Event Propagation 이라고 합니다 )
해결법은 [공식 문서](https://react.dev/learn/responding-to-events#event-propagation)를 참고하면 됩니다. ( Stopping Propagation 파트를 참고해주세요 )

아래는 참고용으로 작성해본 코드 입니다. 똑같이 만들필요는 없고 참고만 해주시면 됩니다.
```javascript
import React from 'react';

import PropTypes from 'prop-types';

const Modal = ({ children, isOpen, setIsOpen, onClose, outsideClose }) => {
  const handleClose = () => {
    onClose();
    setIsOpen(false);
  };

  if (!isOpen) return null;
  return (
    <div
      aria-hidden="true"
      onClick={outsideClose ? handleClose : null}
      className="z-50 h-screen w-screen fixed top-0 left-0 flex flex-col justify-center items-center bg-opacity-50 bg-black"
    >
      <div
        aria-hidden="true"
        onClick={(e) => e.stopPropagation()}
        className="absolute h-60 w-[28rem] bg-white shadow-xl"
      >
        {children}
        <button type="button" onClick={handleClose}>
          Close Modal
        </button>
      </div>
    </div>
  );
};

Modal.propTypes = {
  children: PropTypes.node.isRequired,
  isOpen: PropTypes.bool.isRequired,
  setIsOpen: PropTypes.func.isRequired,
  onClose: PropTypes.func,
  outsideClose: PropTypes.bool,
};

Modal.defaultProps = {
  onClose: () => {},
  outsideClose: false,
};

export default Modal;
```
 aria-hidden="true"는 스크린리더와 같은 보조기술의 탐색을 제한하는 기능이라고 합니다. div에 onClick을 넣었을때 나오는 웹 표준 에러를 해소하기 위해 넣었습니다. 마우스를 사용하지 못하는 사용자를 위한 key event가 필요하다는 내용인데 본질적인 해소법은 아니지만 가장 간단하게 지킬수 있을듯 하네요.

공통컴포넌트의 경우 여러페이지에서 함께 사용하는 코드다 보니 리뷰가 좀 많이 길어졌습니다.....

추가로, 공통컴포넌트 PR은 설명에 간단한 컴포넌트 사용법을 적어주면 좋을듯 합니다!

2023-12-08 14:03 UTC, jasper200207 commented on src/components/Modals/Modal.jsx
> +    <div className="z-[999] h-screen w-screen fixed top-0 left-0 flex flex-col justify-center items-center bg-opacity-50 bg-black">
useEffect와 useRef를 이용하는 방식 대신 onClick 메소드로 구현하면 좋을 듯합니다.
여기 onClick 추가하고 밑에 클릭 중복 안되도록 하면 됩니다. 자세한건 리뷰로 달아놓겠습니다.

2023-12-08 14:03 UTC, jasper200207 commented on src/components/Modals/Modal.jsx
> +const Modal = ({ children, isOpen, setIsOpen, outsideClose }) => {
그리고 해당 `Modal` 컴포넌트에서는  `onClose`를 props로 받은 후 닫았을 때, 이벤트를 정의하는 편이 확장성에 좋아보입니다.

추가적으로 함수명 정할때,
실제 이벤트와 연관되어 있는 경우에는 `on`,
이벤트시 호출되는 함수는 `handle`,
을 붙이면 좋을 듯 합니다.

예를 들면
`onOutsideClick={handleOutsideClick}` 으로 생각하면 될듯 합니다.

2023-12-08 14:03 UTC, jasper200207 commented on src/components/Modals/ConfirmModal.jsx
> +const ConfirmModal = ({ children, isOpen, setIsOpen, outsideClose, closeText, confirmText, confirmEvent }) => {
밑에 Modal.jsx 리뷰와 같이 함수 이름 맞추면 좋을 듯 합니다.

2023-12-22 06:36 UTC, hdh4952 commented on src/components/Modals/ConfirmModal.jsx
> +const ConfirmModal = ({ children, isOpen, setIsOpen, outsideClose, closeText, confirmText, confirmEvent }) => {
리뷰 감사합니다 👍

2023-12-22 08:51 UTC, jasper200207 approved these changes
👍

2023-12-26 13:16 UTC, jimini1026 approved these changes
확인했습니다

2024-01-01 11:29 UTC, kbs1027 approved these changes
LGTM

2024-01-01 11:30 UTC, merged