feat : 프로필 페이지
Untoc-Web-Develop/Untoc-Front pull request #59
Opened 2023-12-30 11:59 UTC by jimini1026

## 관련이슈

- #58

## 요약

프로필 페이지 입니다

## 상세

- UI 개발
- 기능구현 미완성

## 리뷰안내

- 리뷰 예상 소요 시간 : 15분
- 참고사항 : 코드가 난잡한 감이 있습니다...쓴소리 부탁합니다..
- 프리뷰이미지
![image](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/5cf685ec-8a1b-43ee-a707-9dd9a8d5b783)

2024-01-01 11:42 UTC, kbs1027 requested changes

2024-01-01 11:42 UTC, kbs1027 commented on src/page/Profile/Profile.jsx
> +    <div className="w-[1000px] h-auto mx-auto mt-14">
px이 너무 큽니다

2024-01-01 11:48 UTC, hdh4952 requested changes
피그마 디자인 맞춰서 개발 부탁드려요

2024-01-08 13:34 UTC, hdh4952 approved these changes
잘짰네요

2024-01-08 13:34 UTC, hdh4952 commented on src/page/Profile/Profile.jsx
> +            </div>
<Link /> 태그를 사용하면 좀 더 좋을 것 같습니다!

2024-01-08 13:56 UTC, parkqjunseo approved these changes
👍..수고하셨습니다

2024-01-17 02:23 UTC, kbs1027 approved these changes
수고하셨습니다

2024-01-27 14:10 UTC, merged