feat: 팀리스트 목록 페이지
Untoc-Web-Develop/Untoc-Front pull request #75
Opened 2024-02-11 07:27 UTC by jimini1026

## 관련이슈

- #72 

## 요약

팀리스트 목록 페이지 UI

## 상세

- Mui 사용
- header 컴포넌트 새로 제

## 리뷰안내

- 리뷰 예상 소요 시간: 5분
- 프리뷰이미지
![localhost_3000_teamlist](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/d2113d32-db28-446b-9084-66029703cc81)

2024-02-11 07:45 UTC, parkqjunseo approved these changes
잘했네용...수고하셨습니다 👍👌

2024-02-11 13:09 UTC, hdh4952 approved these changes
좋습니다~!

2024-02-11 13:09 UTC, hdh4952 commented on src/components/TeamListHeader/TeamListHeader.jsx
> +
변수를 만들어 사용하는 방법도 괜찮지만, 변수를 한 번만 사용한다면
```javascript
isTeamed ? <Link to="/teamlist/info">내팀 정보</Link> : <Link to="/teamlist/build">팀 빌딩</Link>
```
이런식으로 바로 넣어도 괜찮은 방법일 것 같네요 👍

2024-02-13 06:01 UTC, jimini1026 commented
> 잘했네용...수고하셨습니다 👍👌

.

2024-02-13 11:39 UTC, jasper200207 approved these changes
👍

2024-02-13 12:49 UTC, jasper200207 requested changes
😢

2024-02-13 13:25 UTC, jasper200207 approved these changes
👍

2024-02-13 13:32 UTC, merged