feat : 팀리스트 빌딩 페이지
Untoc-Web-Develop/Untoc-Front pull request #78
Opened 2024-02-13 14:02 UTC by jimini1026

## 관련이슈

- #73 

## 요약

팀리스트 빌딩 페이지 UI

## 상세

- 기능 미완

## 리뷰안내

- 리뷰 예상 소요 시간 : 5분
- 프리뷰이미지
![localhost_3000_teamlist_build](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/6634f8d4-7a5f-4010-8862-6ead35c33ee6)

2024-02-18 11:52 UTC, hdh4952 approved these changes
LGTM

2024-02-26 01:33 UTC, kbs1027 approved these changes
lgtm

2024-03-03 05:11 UTC, mun-kyeong requested changes
수고하셨습니다!! 
아래 코멘트 확인해주시고, 수정 완료되면 말씀해주십쇼
어차피 나중에 수정해야하는 부분이라 지금 작동되게끔 수정하는게 좋을 것 같아서 block 해두겠습니당

2024-03-03 05:11 UTC, mun-kyeong commented on src/page/TeamListBuild/TeamListBuild.jsx
> +                  <input className="w-[15rem] border-b p-1" placeholder="NONE" />
이부분 placeholder를 none으로 하지말고 위에 placeholder랑 통일했으면 좋겠습니다
ex) http://github.com/lead 
이런식으로? 

아니면 URL1, URL2 이런식으로 대체해도 될 것 같아요!! 
> 결론 : 위, 아래의 input placeholder 값 형식이 통일되었으면 합니당

2024-03-03 05:11 UTC, mun-kyeong commented on src/page/TeamListBuild/TeamListBuild.jsx
> +              </label>
이부분 input창에서 이미지 클릭했을때 프로필 이미지쪽에 미리보게 하는건 api 없이도 가능합니다!!
아래 링크 참고해서 확인하시면 될 것 같아요
[이미지 미리보기 구현](https://velog.io/@hye_rin/React-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%97%85%EB%A1%9C%EB%93%9C%ED%95%98%EA%B3%A0-%EB%AF%B8%EB%A6%AC%EB%B3%B4%EA%B8%B0)

우선 시간이 좀 없을 것 같아서 아래에 작동되는 코드 첨부해두겠습니당.
바로 따라쓰기보다 작동 원리를 알고 있으면 그래도 좋지 않을까, 싶긴하지만 그건 자유에 맡기겠습니다!

```javascript
import React, { useState } from 'react';

import teamDefalutImg from 'asset/teamlist/teamDefaultImg.jpg';
import TeamListHeader from 'components/TeamListHeader/TeamListHeader';

const TeamListBuild = () => {
  const [teamImg, setTeamImg] = useState(null);

  const getTeamImg = (e) => {
    const img = e.target.files[0];
    const reader = new FileReader();
    reader.readAsDataURL(img);
    reader.onload = () => {
      setTeamImg(reader.result);
    };
  };

  return (
...

              <img className="h-20 w-20 rounded-full" src={teamImg || teamDefalutImg} alt="이미지" />
              <label htmlFor="teamImgInput">
                <div className="flex h-7 w-[7rem] cursor-pointer items-center justify-center bg-grayLight text-xs text-grayDark">
                  사진 불러오기
                </div>
                <input className="h-0 w-0" type="file" id="teamImgInput" accept="image/*" onChange={getTeamImg} />
              </label>


...
```

위의 코드 참고해서 이미지 불러오는거 구현부탁드립니다!

2024-03-03 05:11 UTC, mun-kyeong commented on src/page/TeamListBuild/TeamListBuild.jsx
> +                src="https://mblogthumb-phinf.pstatic.net/MjAyMDExMDFfMjIg/MDAxNjA0MjI4ODc1MDkx.itxFQbHQ_zAuNQJU7PCOlF0mmstYn2v4ZF4WygunqGIg.3jloNowx-eWU-ztCLACtYubVbATNdCFQLjgvYsynV1og.JPEG.gambasg/
이미지 부분은 아래에 수정해둔것처럼 해당 이미지를 다운받아서 `asset/teamlist/이미지 이름` 이런식으로 저장 한 뒤 import 해서 사용하는 방식으로 수정 부탁드립니다!
가독성을 위해서이기도 하고, 변수로 설정해두면 찾기 쉬움 + (이미지를) 변경하기 쉽다, 라는 장점이 있습니다 :)

2024-03-03 05:11 UTC, mun-kyeong commented on src/page/TeamListBuild/TeamListBuild.jsx
> +                <input className="w-[15rem] border-b p-1" placeholder="+ 팀원 추가하기" />
이거 이부분도 input이 아니라 `팀원 추가하기` 라는 button을 눌렀을 때 실제로 input창이 생겨나는 쪽으로 수정해야 할 것 같습니다!!

아래 코드참고해주세요

```javascript
 const [inputCount, setInputCount] = useState(0);
const deleteMemberInput = (e) => {
    e.target.parentNode.remove();
  };

  const addMemberInput = () => {
    setInputCount(inputCount + 1);
  };

  const renderInputs = () => {
    const inputs = [];
    for (let i = 0; i < inputCount; i += 1) {
      inputs.push(
        <div key={i}>
          <input className="w-[15rem] border-b p-1" placeholder="팀원 이름" />
          <button type="button" onClick={deleteMemberInput}>
            X
          </button>
        </div>,
      );
    }
    return inputs;
  };

  return (
...
                <input className="w-[15rem] border-b  p-1" placeholder="팀원 이름" />
                <input className="w-[15rem] border-b p-1" placeholder="팀원 이름" />
                <input className="w-[15rem] border-b p-1" placeholder="팀원 이름" />
                {renderInputs()}
                <button
                  className="w-[15rem]   p-1 text-xs text-grayDark"
                  id="addTeamInput"
                  type="button"
                  onClick={addMemberInput}
                >
                  + 팀원 추가하기
                </button>

...


```

위의 코드 사용했을 때 삭제 버튼을 누르면 새로 생긴 input창이 삭제되고, 
"팀원 추가하기" 버튼을 눌렀을 때 input창이 추가됩니다.

마찬가지로, 참고용 코드로 사용하셔도 되고 직접 만들어보셔도 될 것 같네욤!
우선 `팀원 추가하기` 는 input창이 아니라 button 용도로 사용 가능하도록 수정해주시면 될 것 같습니다 :)

추가로, 
<img width="598" alt="image" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/96461334/e4b18850-0e13-4382-9ea5-937feb7934af">

위의 사진 참고하셔서 h-fit 조건을 조금 수정해야 input창이 늘어나더라도 해당 노드가 겹쳐보이는 현상을 방지할 수 있을 것 같습니다.

2024-03-03 11:48 UTC, parkqjunseo approved these changes

2024-03-05 13:27 UTC, mun-kyeong approved these changes
수고하셨습니다!!

2024-03-05 15:09 UTC, merged