Feature/메인화면 information 레이아웃 설정 #30
Untoc-Web-Develop/Untoc-Front pull request #81
Opened 2024-02-17 08:17 UTC by mun-kyeong

## 관련이슈

- close #30 

## 요약

- 메인화면의 information 파트 입니다

## 상세

- 메인화면 배경 수정완료했습니다

- constants 폴더 안에 `devTerm` 이라는 파일 명으로 개발용어 더미데이터 만들어두었습니다. 
이중 랜덤으로 하나가 선택되어 메인화면에 보여지는 방식입니다

- ImgToolTip이라는 공통 컴포넌트가 하나 제작되었습니다.
  - 역할은 이번 개발에 사용한 노란색 캐릭터 일러스트의 경우, 상업적 용도로까지 **무료로 사용가능**하지만, 
  **출처를 기입**해야한다는 조건이 있습니다. 
  
  이를 해결하기 위한 컴포넌트로, 구성은 아래와 같습니다. 
  
  ```html
   <Tooltip {...props} classes={{ popper: className }}>
    <img src={props.src} alt={props.alt} className={props.classNamed} />
  </Tooltip>
  ```

  - 사용방법은 `<ImgToolTip>` 의 props를 통해 사용가능합니다.
 
  ```html
   <ImgTooltip title="https://storyset.com/business" src={TeamImg} alt="teamImg" classNamed="w-1/2" />
   //<ImgTooltip title={출처} src={이미지} alt={이미지 alt} classNamed={img에 주려는 속성} />
  ```
  - 참고로 마지막 img에 속성을 주려면 **className** 이 아니라 **classNamed** 입니다..  
  className으로 props를 받으니까 모종의 이유 (아마 Tooltip 자체의 clsass값에 의한 충돌? )로 적용이 안되더라구요
   
## 리뷰안내

- 리뷰 예상 소요 시간 : 10s
- 참고사항 : 없음니닷
- 
<img width="960" alt="image" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/96461334/32ec93e4-3921-478f-a069-04d9e8e7a277">

- 
<img width="521" alt="image" src="https://github.com/Untoc-Web-Develop/Untoc-Front/assets/96461334/2fade42c-da19-488b-a26a-06fc63a56e15">

2024-02-18 11:49 UTC, hdh4952 requested changes
mui를 사용해서 제가 잘 모르는 부분이 있을 수 있지만 다시 한 번 검토를 해볼 만한 부분이라 생각해서 확인 부탁합니다.

2024-02-18 11:49 UTC, hdh4952 commented on public/index.html
> +    </style>
스크롤 바를 숨기는 기능은 html 파일보다는 css 파일에 배치하는 편이 좀 더 목적에 맞지 않을까요?

2024-02-18 11:49 UTC, hdh4952 commented on src/components/ImgToolTip/ImgToolTip.jsx
> +
prop-types 라이브러리를 사용해서 필요한 props를 알려주면  컴포넌트 사용이 좀 더 쉬워질 것 같습니다

2024-02-18 11:49 UTC, hdh4952 commented on .eslintrc
> +    "react/jsx-props-no-spreading": "off",
props를 전달할 때 spread 연산자를 사용하는 것을 권장하지 않는 것은 해당 컴포넌트에 필요한 속성을 명시해서 가독성을 높이려는 이유라고 합니다. 
이 eslint 설정을 바꾸기보다는 코드를 개선하는 방법이 좋을 듯 합니다. 만약 코드 개선이 어렵더라도 'off'보다 'warn'을 사용하는 편이 나은 방향일 것 같네요.
참고: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-props-no-spreading.md

2024-02-25 05:19 UTC, mun-kyeong commented on public/index.html
> +    </style>
해결완료입니다~~~tailwind 속성으로 넣어뒀어요

2024-02-25 05:45 UTC, mun-kyeong commented on src/components/ImgToolTip/ImgToolTip.jsx
> +
prop을 풀어써야 한다는 생각을 하지 못했네요..!! 기존에 제공되는 코드를 그대로 쓴다는 생각을 했었습니다 ㅎㅎ
명시적으로 props 써서 가져오는 방식으로 적용해둿습니다!!

2024-02-25 05:46 UTC, mun-kyeong commented on .eslintrc
> +    "react/jsx-props-no-spreading": "off",
위의 ToolTip 코드으l props 수정하면서 스프레드 연산자 관련 옵션 제거했습니다!!
좋은 지적 감사합니다!!

2024-02-25 08:07 UTC, hdh4952 approved these changes
LGTM 👍

2024-02-26 01:34 UTC, kbs1027 approved these changes
lgtm

2024-03-03 11:15 UTC, parkqjunseo approved these changes

2024-03-03 13:54 UTC, merged