feat : 상태 관리
Untoc-Web-Develop/Untoc-Front pull request #98
Opened 2024-03-16 14:01 UTC by jimini1026

## 관련이슈

- #73 

## 요약

작업에 대한 간단한 요약

## 상세

- useForm 통해 상태 관리
- 팀 생성 전 모달창 생성

## 리뷰안내

- 리뷰 예상 소요 시간 : 15분
- 참고사항 : useEffect 1개랑, useState를 몇 개 썼는데 괜찮을까요
- 프리뷰이미지
![image](https://github.com/Untoc-Web-Develop/Untoc-Front/assets/128363259/1a11ccc7-fafd-4553-af88-179ef8847d18)

2024-03-17 06:09 UTC, hdh4952 requested changes
확인바랍니다~

2024-03-17 06:09 UTC, hdh4952 commented on src/page/TeamListBuild/SelectMember.jsx
>    const [value, setValue] = React.useState([]);
value보다 좀 더 의미를 포함한 변수명을 사용하는 게 좋을 것 같습니다

2024-03-17 06:09 UTC, hdh4952 commented on src/page/TeamListBuild/TeamListBuild.jsx
> +/* eslint-disable react/jsx-props-no-spreading */
eslint를 해제하기 보단 맞춰서 작성하는 편이 좋을 것 같네요

2024-03-17 06:09 UTC, hdh4952 commented on src/page/TeamListBuild/TeamListBuild.jsx
> +  };
필요한 함수인가요..? 나중에 구현할 예정이라면 주석으로 TODO 태그를 달아놓는 게 좋아보입니다

2024-03-17 06:18 UTC, kbs1027 requested changes
필요없는 코드를 주석처리 한 것은 지워서 올려주세요, 코드에 대한 설명 정도나 나중에 구현할 함수를 주석처리하여 나둔 것은 괜찮을 것 같습니다

2024-03-17 06:18 UTC, kbs1027 commented on src/page/TeamListBuild/TeamListBuild.jsx
> +/* eslint-disable react/jsx-props-no-spreading */
eslint는 코드의 일관성을 유지하려고 쓰니 해제는 안하는게 좋을 것 같네요
참고: [https://velog.io/@treejy/React-ESLint%EC%99%80-Prettier%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%98%EA%B3%A0-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EC%A7%80](url)

2024-03-17 13:21 UTC, hdh4952 approved these changes
👍

2024-03-20 05:54 UTC, jasper200207 approved these changes
👍

2024-03-25 06:50 UTC, kbs1027 approved these changes
lgtm

2024-03-25 06:51 UTC, merged